<?xml version="1.0" encoding="UTF-8"?>
<!-- You may freely edit this file. See commented blocks below for -->
<!-- some examples of how to customize the build. -->
<!-- (If you delete it and reopen the project it will be recreated.) -->
<!-- By default, only the Clean and Build commands use this build script. -->
<!-- Commands such as Run, Debug, and Test only use this build script if -->
<!-- the Compile on Save feature is turned off for the project. -->
<!-- You can turn off the Compile on Save (or Deploy on Save) setting -->
<!-- in the project's Project Properties dialog box.-->
<project name="PIMS" default="default" basedir=".">
    <description>Builds, tests, and runs the PIMS project.</description>
    <!-- nbproject/build-impl.xml does not exist yet - NetBeans generates it
         automatically the first time you open this project in the IDE. -->
    <import file="nbproject/build-impl.xml"/>
</project>
